### ISSUE TITLE
Syntax error in "OCaml has some new shiny syntax"

### ISSUE THREAD

**Issue by glionnet** [jobjo/jobjo.github.io#3]
There is a `)` missing leading to a syntax error in this code snipet

>Going the other way around, one can also express `product` using `pure` and `apply`:
>```ocaml
>let product xa ya = pure (fun x y -> (x, y) <*> xa <*> ya
>```

**Comment by jobjo** [comment]
@glionnet, thanks. Addressed.

**Comment by jobjo** [comment]
Fixed.
